version: '3'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - "./.env.dev"
    depends_on:
      - db-postgres
    volumes:
      - static_data:/usr/src/app/staticfiles
      - media_data:/usr/src/app/media

  db-postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - "./.env.dev"
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_data:/var/www/static/
      - media_data:/var/www/media/
      - ./frontend/build:/usr/share/nginx/html # Frontend static

    depends_on:
      - backend
      - db-postgres
    ports:
      - 80:80


volumes:
  pg_data:
  static_data:
  media_data: